name: "CI -> Security"
on:
  branch_protection_rule:
  schedule:
    - cron: "33 3 * * 1"

  push:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - ".*ignore"

  pull_request:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - ".*ignore"

permissions: read-all

jobs:
  codeql:
    name: "CodeQL"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript-typescript

    permissions:
      security-events: write

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          persist-credentials: false

      - name: "Setup CodeQL"
        uses: github/codeql-action/init@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
        with:
          languages: ${{ matrix.language }}

      - name: "Run analysis"
        uses: github/codeql-action/analyze@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
        with:
          category: "/language:${{ matrix.language }}"

  scoreboard:
    name: "Scorecard"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_file: scoreboard.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
        with:
          sarif_file: scoreboard.sarif
